sudo: required
services: 
  - docker

before_install:
  - docker build -t nkowsik86/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nkowsik86/react-test npm run test -- --coverage

after_success:
  - docker build -t nkowsik86/multi-client ./client
  - docker build -t nkowsik86/multi-nginx ./nginx
  - docker build -t nkowsik86/multi-server ./server
  - docker build -t nkowsik86/multi-worker ./worker
  # Take those image and push them to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nkowsik86/multi-client
  - docker push nkowsik86/multi-nginx
  - docker push nkowsik86/multi-server
  - docker push nkowsik86/multi-worker